#!/usr/bin/env python

import os
import sys
import getopt

import smache

def usage():
    sys.stderr.write("usage: %s [--log=<file>] [--verbose] [--help] <config>\n" % sys.argv[0])

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "l:vh", ["log=", "verbose", "help"])
    except getopt.GetoptError, err:
        print str(err)
        usage()
        sys.exit(2)

    log = None

    # Parse all options.
    for o, a in opts:
        if o in ("-l", "--log"):
            log = a
        elif o in ("-v", "--verbose"):
            smache.setLogLevel(smache.getLogLevel())
        elif o in ("-h", "--help"):
            usage()
            sys.exit()

    # Send our logs to the appropriate place.
    if log:
        se = open(log, 'a+', 0)
        os.dup2(se.fileno(), sys.stderr.fileno())

    # Check that we have a config.
    if len(args) == 0:
        sys.stderr.write("unable to start without a config\n")
        usage()
        sys.exit(1)

    # Load the configs.
    c = smache.Config(args)

    # Run everything.
    smache.go(c)

if __name__ == "__main__":
    main()
