#!/usr/bin/python

import smache
import smache.fs
import sys

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print "usage: %s <smache.config> <mountpoint> [fuse options...]" % sys.argv[0]
        sys.exit(1)
    
    spec  = smache.Config(sys.argv[1])
    store = smache.FileStore(spec)
    fs    = smache.fs.FS(store)

    newargs = [sys.argv[0]]
    newargs.extend(sys.argv[2:])
    sys.argv = newargs
    fs.parse(errex=1)

    fs.main()
