#!/usr/bin/env python

import smache
import sys
import os
import stat

def usage(args):
    print "usage: %s <smache.config>" % (args[0])

def main(args):
    if not(len(args) == 2):
        usage(args)
        return

    #
    # Create a smache instance.
    #
    spec  = smache.Config(sys.argv[1])
    store = smache.FileStore(spec)
    stats = store.getstats()
    stats.dump()

if __name__ == "__main__":
    main(sys.argv)
