#!/usr/bin/env python

import smache
import sys
import os
import stat

def usage(args):
    print "usage: %s <x|a|l> <smache.config> [files....]" % (args[0])
    print " l - List available files."
    print " x - Extract listed files."
    print " a - Add listed files."

def main(args):
    if len(args) < 3:
        usage(args)
        return

    #
    # Create a smache instance.
    #
    spec  = smache.Config(sys.argv[2])
    store = smache.FileStore(spec)

    #
    # Actually extract/add appropriate files.
    #
    if args[1] == "x":
        if len(args) == 3:
            store.extract(store.list())
        else:
            store.extract(args[3:])

    elif args[1] == "a":
        store.add(args[3:])

    elif args[1] == "l":
        for f in store.list():
            print f

    store.save()

if __name__ == "__main__":
    main(sys.argv)
